In [1]:
import numpy as np

Basics

In [2]:
a = np.array([1,2,3])

In [5]:
a.shape

(3,)

In [6]:
a.size

3

In [7]:
b = np.array([2,3,6,])

In [13]:
b

array([2, 3, 6])

In [8]:
a*b

array([ 2,  6, 18])

In [9]:
c = np.array([[1,2,3], [2,3,5,]])

In [14]:
c

array([[1, 2, 3],
       [2, 3, 5]])

In [11]:
c.size
c.shape

(2, 3)

In [12]:
c.ndim #gives dimensions

2

Changing and acessing of arrays

In [16]:
a[:]

array([1, 2, 3])

In [19]:
d = np.array([[[1,2,3],[4,5,6]], [[8,9,0], [2,5,8,]]])

In [20]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[8, 9, 0],
        [2, 5, 8]]])

In [21]:
#first value indicates which matrix, second the row and third shows columns

d[0,1,1]

5

In [24]:
d[1,1,0] = 6 

In [25]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[8, 9, 0],
        [6, 5, 8]]])

In [26]:
d[:,1,:]

array([[4, 5, 6],
       [6, 5, 8]])

types of arrays

In [31]:
np.identity(10, dtype = 'int32') 

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [37]:
np.zeros(((((3,3,3,3,3)))))

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
    

In [38]:
np.full((2,2), 2) # first is the array size and second is the value

array([[2, 2],
       [2, 2]])

In [50]:
np.random.rand(4,2,3)

array([[[0.12489376, 0.49386899, 0.29072577],
        [0.97753516, 0.32977675, 0.545282  ]],

       [[0.82428103, 0.41386729, 0.95024116],
        [0.49175054, 0.72112778, 0.66088053]],

       [[0.33221238, 0.24948664, 0.80054703],
        [0.51375965, 0.76592854, 0.69340214]],

       [[0.85990236, 0.56064032, 0.69530218],
        [0.87646592, 0.88589683, 0.40614908]]])

###copying

In [53]:
i = np.array([1,2,3])
j = i

j[0] = 4
i

array([4, 2, 3])

In [57]:
#to avoid what happened above

i = np.array([1,2,3])
j = i.copy()

j[0] = 4
i


array([1, 2, 3])

##mathemmatics

In [59]:
i=i+2
i

array([3, 4, 5])

In [60]:
j = j/2
j

array([2. , 1. , 1.5])

In [67]:
h = np.full((3,2), 2)
k = np.full((2,3), 3)
k

array([[3, 3, 3],
       [3, 3, 3]])

In [62]:
np.matmul(h,k)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

stats

In [63]:
np.min(h)

2

In [71]:
np.sum(k)

18

Rorganizing

Stacking